#importing libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset


In [2]:
traindataset = pd.read_csv('Training.csv')
testdataset = pd.read_csv('Testing.csv')
df_train = pd.read_csv('Training.csv', delimiter=',')
# x = dataset.iloc[:, :-1].values
# y = dataset.iloc[:, -1].values
# k=y
# diseases=y
symptoms=np.array(df_train.columns)

#Splitting the dataset into the Training set and Test set

In [3]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(x, diseases, test_size = 0.15, random_state = 0)
X_train =traindataset.iloc[:, :-1].values
y_train=traindataset.iloc[:, -1].values
X_test =testdataset.iloc[:, :-1].values
y_test=testdataset.iloc[:, -1].values

In [4]:
print(y_train)

['Fungal infection' 'Fungal infection' 'Fungal infection' ...
 'Urinary tract infection' 'Psoriasis' 'Impetigo']


In [5]:
print(y_test)

['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo']


#Training the random forest model on the Training set


In [6]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

#Predicting a new result

In [7]:
description = np.array(input("Describe your symptoms: ").split())

Describe your symptoms: itching


In [8]:
s=np.zeros(132)
i=0
for x in symptoms:
   if x in  description:
      print(x)
      s[i]=1
   i+=1

itching


In [9]:
B = s.reshape(1,132)
print(B)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
print(classifier.predict(B))

['Fungal infection']


In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Fungal infection' 'Fungal infection']
 ['Allergy' 'Allergy']
 ['GERD' 'GERD']
 ['Chronic cholestasis' 'Chronic cholestasis']
 ['Drug Reaction' 'Drug Reaction']
 ['Peptic ulcer diseae' 'Peptic ulcer diseae']
 ['AIDS' 'AIDS']
 ['Diabetes ' 'Diabetes ']
 ['Gastroenteritis' 'Gastroenteritis']
 ['Bronchial Asthma' 'Bronchial Asthma']
 ['Hypertension ' 'Hypertension ']
 ['Migraine' 'Migraine']
 ['Cervical spondylosis' 'Cervical spondylosis']
 ['Paralysis (brain hemorrhage)' 'Paralysis (brain hemorrhage)']
 ['Jaundice' 'Jaundice']
 ['Malaria' 'Malaria']
 ['Chicken pox' 'Chicken pox']
 ['Dengue' 'Dengue']
 ['Typhoid' 'Typhoid']
 ['hepatitis A' 'hepatitis A']
 ['Hepatitis B' 'Hepatitis B']
 ['Hepatitis C' 'Hepatitis C']
 ['Hepatitis D' 'Hepatitis D']
 ['Hepatitis E' 'Hepatitis E']
 ['Alcoholic hepatitis' 'Alcoholic hepatitis']
 ['Tuberculosis' 'Tuberculosis']
 ['Common Cold' 'Common Cold']
 ['Pneumonia' 'Pneumonia']
 ['Dimorphic hemmorhoids(piles)' 'Dimorphic hemmorhoids(piles)']
 ['Heart at

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))


[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
1.0
