#importing libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset


In [2]:
dataset = pd.read_csv('Training.csv')
df_train = pd.read_csv('Training.csv', delimiter=',')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
k=y
diseases=y.reshape(len(y),1)
symptoms=np.array(df_train.columns)
print(x.shape)

(4920, 132)


#Encoding the Independent Variable

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# diseases = np.array(ct.fit_transform(diseases))

#Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.15, random_state = 0)

In [5]:
print(y_train)

['Bronchial Asthma' 'Alcoholic hepatitis' 'Varicose veins' ... 'Allergy'
 'Alcoholic hepatitis' 'Common Cold']


In [6]:
print(y_test)

['Heart attack' 'hepatitis A' 'Tuberculosis' 'Hypoglycemia'
 'Peptic ulcer diseae' 'Hypertension ' 'Osteoarthristis' 'Varicose veins'
 'hepatitis A' 'Typhoid' 'Urinary tract infection' 'Impetigo' 'GERD'
 'Varicose veins' 'Fungal infection' 'Paralysis (brain hemorrhage)'
 'Hypertension ' 'AIDS' 'Hypothyroidism' 'Hypothyroidism' 'AIDS'
 'Hepatitis D' 'Drug Reaction' 'Drug Reaction' 'Pneumonia' 'Common Cold'
 'Urinary tract infection' 'Dimorphic hemmorhoids(piles)' 'Jaundice'
 'Allergy' 'Chronic cholestasis' 'Drug Reaction'
 'Dimorphic hemmorhoids(piles)' 'Hepatitis D' 'Chicken pox' 'Diabetes '
 'Bronchial Asthma' 'Drug Reaction' 'Acne' 'Drug Reaction'
 '(vertigo) Paroymsal  Positional Vertigo' 'Hepatitis E'
 'Peptic ulcer diseae' 'Jaundice' 'Heart attack' 'Urinary tract infection'
 'Hepatitis D' 'Heart attack' 'Dimorphic hemmorhoids(piles)'
 'Varicose veins' 'Hyperthyroidism' 'Urinary tract infection'
 'Peptic ulcer diseae' 'Hepatitis B' 'Typhoid' 'Chicken pox'
 'Dimorphic hemmorhoids(pi

#Training the K-NN model on the Training set


In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

#Predicting a new result

In [8]:
description = np.array(input("Describe your symptoms: ").split())

Describe your symptoms: headache high_fever sweating nausea cold weakness fatigue stomach_pain


In [9]:
s=np.zeros(132)
i=0
for x in symptoms:
   if x in  description:
      s[i]=1
   i+=1

In [10]:
B = s.reshape(1,132)
print(B)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
print(classifier.predict(B))

['Malaria']


In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Heart attack' 'Heart attack']
 ['hepatitis A' 'hepatitis A']
 ['Tuberculosis' 'Tuberculosis']
 ...
 ['Impetigo' 'Impetigo']
 ['Allergy' 'Allergy']
 ['Heart attack' 'Heart attack']]


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred)*100)


[[14  0  0 ...  0  0  0]
 [ 0 17  0 ...  0  0  0]
 [ 0  0 23 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 19]]
100.0
